name: Auto Tag

on:
  pull_request:
    types:
      - closed

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        git fetch --prune --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "::set-output name=latest_tag::$latest_tag"

    - name: Increment the version and create a new tag
      id: increment_version
      uses: juliangruber/increment-version@v1
      with:
        version: ${{ steps.get_latest_tag.outputs.latest_tag }}
        type: patch

    - name: Push the new tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.increment_version.outputs.newVersion }}
        git push origin ${{ steps.increment_version.outputs.newVersion }}
