name: Auto Tag

on:
  pull_request:
    types:
      - closed

jobs:
  auto_tag:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install semver

    - name: Get the latest tag
      id: get_latest_tag
      run: |
        git fetch --prune --unshallow --tags
        latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "::set-output name=latest_tag::$latest_tag"

    - name: Increment the version and create a new tag
      id: increment_version
      run: |
        import os
        import semver

        latest_tag = os.environ["LATEST_TAG"]
        new_version = semver.bump_patch(latest_tag)
        print(f"New version: {new_version}")
        echo "::set-output name=new_version::$new_version"
      env:
        LATEST_TAG: ${{ steps.get_latest_tag.outputs.latest_tag }}
      shell: python

    - name: Push the new tag
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git tag ${{ steps.increment_version.outputs.new_version }}
        git push origin ${{ steps.increment_version.outputs.new_version }}
